#pragma once
#ifndef CHUNK_HPP
#define CHUNK_HPP

#include <vector>

#include <GLFW/glfw3.h>
#include <glm/glm.hpp>

enum class block_type : uint8_t {
	none = 0,
	sand = 1,
	// brick,

	cnt
};

struct chunk_t {
	static constexpr int8_t width = 16;
	static constexpr int8_t height = 16;
	static constexpr int8_t depth = 16;

	std::vector<std::vector<std::vector<block_type>>> content;
	std::vector<std::vector<std::vector<bool>>> is_autogenerated;

	chunk_t();
};

#endif
