#include "chunk.hpp"

chunk_t::chunk_t()
	:content(width,
			std::vector<std::vector<block_type>>(height,
				std::vector<block_type>(depth, block_type::none)))
	,is_autogenerated(width,
			std::vector<std::vector<bool>>(height,
				std::vector<bool>(depth, true)))
{ }
